### ISSUE TITLE
MVPレビュー

### ISSUE THREAD

**Issue by Tsuchiya2** [mugihouse/auto_do_application#114]
MVPリリースお疲れ様でした、下記の視点をもとにレビューいたします。

1. READMEから課題解決する実装がされているか&動いている
2. 静的コードチェックが入っている
3. 就活において十分な技術力を示せる機能を実装しているか
4. UIでユーザーが迷わないような導線を作れているか・ユーザーが使いたくなるようなサービス設計ができているか

## READMEから課題解決する実装がされているか&動いている
LGTMです。

## 静的コードチェックが入っている
・Rubocopを通しましょう。app/controllers/line_bot_messages_controller.rb辺り、1アクション辺りの行数が多すぎる箇所があったりと、Rubocopに引っかかる箇所があるかと思うのでメソッドとして切り出したり、ロジックをモデルに寄せたりしましょう。

## 就活において十分な技術力を示せる機能を実装しているか
・十分な技術力を示せる機能を示せているかに関しては、一定水準を満たしていると思います。
・テストを書きましょう。
・独自ドメイン対応しましょう。
・faviconも対応しましょう。
・追加機能を考えましょう（例：タスクの消化数をグラフ化する・消化しているタスクの傾向からレコメンドする機能etc）。

## UIでユーザーが迷わないような導線を作れているか・ユーザーが使いたくなるようなサービス設計ができているか
・触ってみてですが、大きな違和感は感じませんでした。

上記のレビューをタスクに落とし込み、issueに書きましたら、こちらのissueはcloseしていただいて大丈夫です。
また書き出したissueをもとに本リリースまでのスケジュールを教えていただけますでしょうか？
よろしくお願いいたします。

**Comment by mugihouse** [comment]
レビューありがとうございました！
ご指摘いただいた点の修正を含めてissueに記載したので確認お願いします。

本リリースは10月18日（水）を予定しています。

**Comment by Tsuchiya2** [comment]
ご対応ありがとうございます。
追加機能の方はいかがでしょうか？

**Comment by mugihouse** [comment]
コメントありがとうございます。
「タスクの消化数グラフ化」は本リリースで導入予定だったため、issue化しております。
「消化しているタスクの傾向からレコメンドする機能」については同じタスクばかり推奨されそうなので、他に追加できる機能を検討してからissue化して取り組みたいと思っています。

**Comment by Tsuchiya2** [comment]
承知しました。
サービスがツール系に属するかと思うため、なかなか追加機能の案を考えるのが難しいかと思いますが、それらを実装しながら、どういったものがユーザーに望まれているのか、FBを上手く反映させていくと良いと思います。

引き続き開発頑張ってください。
