### ISSUE TITLE
タスク配信とログを残すためのテーブル設計

### ISSUE THREAD

**Issue by mugihouse** [mugihouse/auto_do_application#73]
ランダムで選んだタスクをLINE BOTで配信するアプリを作成中です。
配信1回目は登録されたタスクの中から1つ選び配信するところまで完成しました。

2回目以降は今日配信していないものの中から1つ選んで配信したいと考えています。
また、本リリース時には実行したタスクの量をグラフ化して見れるようにする予定です。
（グラフの作成はchartkickの導入を検討中）

そのため、配信したタスクの管理をできるようにテーブル設計を変更する必要があると考えています。
ER図が変わってしまうので検討中のもので問題ないかを確認していただきたいです。
よろしくお願いします。

* [x] Task_recordsテーブルを追加
* [x] タスクの配信日(delivery_date)を登録できること
* [x] タスク実行前、実行後がわかるようにstatusカラム作成(enumを使用予定)
* [x] Taskテーブルとリレーションを結ぶ

想定フロー
https://tulip-buffet-65b.notion.site/f1fc8ef5ad744fef8fb9b7d7d0eb3f3a?pvs=4

最初のER図
https://app.diagrams.net/#G1nYNbskVNv_8Xn0WER9LDXoBGjUTsDQ7s

改訂版ER図
https://app.diagrams.net/#G1J7e7lqiPsmzQ6i9WrEAcy2g6653oAzPu

**Comment by Tsuchiya2** [comment]
ER図が見れないようです。
スクリーンショットをコメント欄にアップしてもらえますか？

**Comment by mugihouse** [comment]
失礼しました！
スクリーンショットにてアップしましたので、確認をお願いします。

最初のER図
![image](https://github.com/mugihouse/auto_do_application/assets/114850902/d4cd104f-e1ae-424d-940a-a7a76e96934c)

改訂版ER図
![image](https://github.com/mugihouse/auto_do_application/assets/114850902/32f29294-5a5b-4598-97e1-7de253b13e41)

**Comment by Tsuchiya2** [comment]
おおよそ良いように思いました。
ただ「Task_Records」テーブルの命名は別なものを考えた方が良いかと思いました。
このテーブルが担う役割を元に命名を考えてみましょう。通知などであればnotificationsなどでも良いかもしれません。

**Comment by mugihouse** [comment]
- [ ]  rails g model Notification delivery_date:time status:integer task:references

モデル
- [ ]  statusカラムにenumで実行前と実行後を追加
- [ ]  belongs_to :task
- [ ]  has_many :notifications
